export const ADD_CONNECTION = 'ADD_CONNECTION'
export const REMOVE_CONNECTION = 'REMOVE_CONNECTION'
export const SET_CURRENT_CONNECTION = 'SET_CURRENT_CONNECTION'
export const UPDATE_TABLE_LIST = 'UPDATE_TABLE_LIST'
